/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.so.agi.ilirepositorize;

import org.junit.Test;

import ch.so.agi.ilirepositorize.App;

import static org.junit.Assert.*;

public class AppTest { }
